server:
  port: 8193
  servlet:
    context-path: /auth-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
jwt:
  lifetime: 36000000
  secret: kfhksdfdskafhkjsahfkjsahfkajfhakjf