server:
  port: 8191
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  config:
    import: security.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/market
market:
  storage:
    path: files
#      keycloak:
#        issuer-uri: http://localhost:8083/auth/realms/market