server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8190"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://localhost:8191
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/prod-service
        - id: cart-service
          uri: http://localhost:8192
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service
        - id: order-service
          uri: http://localhost:8193
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/market
        registration:
          core-client:
            provider: keycloak
            client-id: core-client
            client-secret: qbXBGMia8U3GapRcOu5tnnFxWUC5CujG
            scope:
              - read
              - write