server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8190/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://localhost:8191
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/prod-service
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8192
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:8193
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8180
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8083/auth/realms/market
#        registration:
#          core-client:
#            provider: keycloak
#            client-id: core-client
#            client-secret: 9n6vrmsDdOSWb6a9BYYq6AkK20VO8Uad
#            scope:
#              - read
#              - write