server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8190"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://localhost:8191
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/prod-service
        - id: cart-service
          uri: http://localhost:8192
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service