
server:
  port: 8193
spring:
  config:
    import: secret.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: ru.grabovsky.cartservice.dto.OrderDto
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/market
logging:
  level:
    ru:
      grabovsky: debug
kafka:
  group-id: orders
  server: localhost:9092